project: 
  type: website
  output-dir: docs
  
website:
  title: "L'AGD pour le traitement des questions ouvertes"
  
  navbar:
    type: inverse
    left:
      - text: "Supports"
        menu:
        - text: "Concepts de statistique textuelle"
          href: Intro.qmd
        - text: "Pas-à-pas avec R"
          href : QO_Pee_K1.qmd
        - text: "Premiers pas avec Spad"
          href : diaspad.qmd
      - text: "Mise en oeuvre avec un corpus"
        href: Exercices_enonces.html
        
      - text: "Ressources"
        href: biblio.html
    right:
      - icon: github
        href: http://github.com/benegarbi
format:
  html: 
    theme: 
     - cosmo
     - mystyle.scss
    toc: true
    toc-depth: 3
    
execute:
  freeze: auto
